# Security routes
api_login:
    path: /api/login
    controller: App\Controller\SecurityController::login
    methods: [POST]

api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: [POST]

api_classes:
    path: /api/classes
    controller: App\Controller\GameDataController::getClasses
    methods: [GET]

api_races:
    path: /api/races
    controller: App\Controller\GameDataController::getRaces
    methods: [GET]

api_create_character:
    path: /api/create-character
    controller: App\Controller\CharacterController::createCharacter
    methods: [POST]

api_user_characters:
    path: /api/user-characters/{id}
    controller: App\Controller\CharacterController::createCharacter
    methods: [GET]